=== esgaltur/soapui2postman/src/main/resources/schema/collection.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://schema.getpostman.com/json/draft-07/collection/v2.1.0/",
  "type": "object",
  "properties": {
    "info": {
      "$ref": "info.json"
    },
    "item": {
      "type": "array",
      "description": "Items are the basic unit for a Postman collection. You can think of them as corresponding to a single API endpoint. Each Item has one request and may have multiple API responses associated with it.",
      "items": {
        "title": "Items",
        "oneOf": [
          {
            "$ref": "item.json"
          },
          {
            "$ref": "item-group.json"
          }
        ]
      }
    },
    "event": {
      "$ref": "event-list.json"
    },
    "variable": {
      "$ref": "variable-list.json"
    },
    "auth": {
      "oneOf": [
        {
          "type": "null"
        },
        {
          "$ref": "auth.json"
        }
      ]
    },
    "protocolProfileBehavior": {
      "$ref": "protocol-behavior.json"
    }
  },
  "required": [
    "info",
    "item"
  ]
}

=== esgaltur/soapui2postman/src/main/resources/testProject/result.json
{
  "info": {
    "name": "https://run.mocky.io",
    "_postman_id": "1aeb5519-88ea-485f-a799-8df2136e6c97",
    "schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
  },
  "item": [
    {
      "name": "GET",
      "variable": [],
      "event": [],
      "request": {
        "url": {
          "raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1",
          "protocol": "https",
          "host": "run.mocky.io",
          "path": [
            "v3",
            "64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
          ],
          "port": "",
          "query": [],
          "variable": []
        },
        "auth": {
          "type": "basic",
          "apikey": [],
          "awsv4": [],
          "basic": [
            {
              "key": "username",
              "value": "test",
              "type": "string"
            },
            {
              "key": "password",
              "value": "test",
              "type": "string"
            }
          ],
          "bearer": [],
          "digest": [],
          "edgegrid": [],
          "hawk": [],
          "ntlm": [],
          "oauth1": [],
          "oauth2": []
        },
        "method": "GET",
        "header": [
          {
            "key": "a",
            "value": "1",
            "disabled": false,
            "description": ""
          }
        ],
        "body": {
          "mode": "raw",
          "raw": "",
          "urlencoded": [],
          "formdata": [],
          "options": {
            "raw": {
              "language": "json"
            }
          },
          "disabled": false
        }
      },
      "response": []
    },
    {
      "name": "POST",
      "variable": [],
      "event": [],
      "request": {
        "url": {
          "raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1",
          "protocol": "https",
          "host": "run.mocky.io",
          "path": [
            "v3",
            "64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
          ],
          "port": "",
          "query": [],
          "variable": []
        },
        "auth": {
          "type": "basic",
          "apikey": [],
          "awsv4": [],
          "basic": [
            {
              "key": "username",
              "value": "test",
              "type": "string"
            },
            {
              "key": "password",
              "value": "test",
              "type": "string"
            }
          ],
          "bearer": [],
          "digest": [],
          "edgegrid": [],
          "hawk": [],
          "ntlm": [],
          "oauth1": [],
          "oauth2": []
        },
        "method": "POST",
        "header": [
          {
            "key": "x-test-json-header",
            "value": "{\"a\":\"b\"}",
            "disabled": false,
            "description": ""
          },
          {
            "key": "a",
            "value": "",
            "disabled": false,
            "description": ""
          }
        ],
        "body": {
          "mode": "raw",
          "raw": "{\"someField\": \"SomeValue\"}",
          "urlencoded": [],
          "formdata": [],
          "options": {
            "raw": {
              "language": "json"
            }
          },
          "disabled": false
        }
      },
      "response": []
    },
    {
      "name": "PUT",
      "variable": [],
      "event": [],
      "request": {
        "url": {
          "raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1",
          "protocol": "https",
          "host": "run.mocky.io",
          "path": [
            "v3",
            "64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
          ],
          "port": "",
          "query": [],
          "variable": []
        },
        "auth": {
          "type": "basic",
          "apikey": [],
          "awsv4": [],
          "basic": [
            {
              "key": "username",
              "value": "test",
              "type": "string"
            },
            {
              "key": "password",
              "value": "test",
              "type": "string"
            }
          ],
          "bearer": [],
          "digest": [],
          "edgegrid": [],
          "hawk": [],
          "ntlm": [],
          "oauth1": [],
          "oauth2": []
        },
        "method": "PUT",
        "header": [
          {
            "key": "x-test-json-header",
            "value": "{\"a\":\"b\"}",
            "disabled": false,
            "description": ""
          },
          {
            "key": "a",
            "value": "",
            "disabled": false,
            "description": ""
          }
        ],
        "body": {
          "mode": "raw",
          "raw": "{\"someField\": \"SomeValue\"}",
          "urlencoded": [],
          "formdata": [],
          "options": {
            "raw": {
              "language": "json"
            }
          },
          "disabled": false
        }
      },
      "response": []
    }
  ],
  "event": [],
  "variable": []
}

=== esgaltur/soapui2postman/src/main/resources/testProject/TestCollection.postman_collection.json
{
	"info": {
		"_postman_id": "ce19dcc1-a161-45f2-b18c-4d26699a2903",
		"name": "TestCollection",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "GET",
			"request": {
				"auth": {
					"type": "basic",
					"basic": [
						{
							"key": "password",
							"value": "test",
							"type": "string"
						},
						{
							"key": "username",
							"value": "test",
							"type": "string"
						}
					]
				},
				"method": "GET",
				"header": [
					{
						"key": "x-test-header",
						"value": "1245678",
						"type": "text"
					},
					{
						"key": "x-json-test-header",
						"value": "{\"a\":\"b\"}",
						"type": "text"
					},
					{
						"key": "x-string-header",
						"value": "asdsadasd",
						"type": "text"
					}
				],
				"url": {
					"raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1?a=1",
					"protocol": "https",
					"host": [
						"run",
						"mocky",
						"io"
					],
					"path": [
						"v3",
						"64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
					],
					"query": [
						{
							"key": "a",
							"value": "1"
						}
					]
				}
			},
			"response": [
				{
					"name": "GET",
					"originalRequest": {
						"method": "GET",
						"header": [
							{
								"key": "x-test-header",
								"value": "1245678",
								"type": "text"
							},
							{
								"key": "x-json-test-header",
								"value": "{\"a\":\"b\"}",
								"type": "text"
							},
							{
								"key": "x-string-header",
								"value": "asdsadasd",
								"type": "text"
							}
						],
						"url": {
							"raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1?a=1",
							"protocol": "https",
							"host": [
								"run",
								"mocky",
								"io"
							],
							"path": [
								"v3",
								"64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
							],
							"query": [
								{
									"key": "a",
									"value": "1"
								}
							]
						}
					},
					"status": "OK",
					"code": 200,
					"_postman_previewlanguage": "json",
					"header": [
						{
							"key": "x-some-header",
							"value": "1234"
						},
						{
							"key": "Content-Type",
							"value": "application/json; charset=UTF-8"
						},
						{
							"key": "Date",
							"value": "Sat, 20 Feb 2021 14:53:24 GMT"
						},
						{
							"key": "Content-Length",
							"value": "27"
						},
						{
							"key": "Sozu-Id",
							"value": "13b3d57f-0aaa-4b66-ae3d-96980872b1bd"
						}
					],
					"cookie": [],
					"body": "{\n    \"someField\": \"SomeValue\"\n}"
				}
			]
		},
		{
			"name": "POST",
			"protocolProfileBehavior": {
				"disabledSystemHeaders": {
					"content-type": true
				}
			},
			"request": {
				"auth": {
					"type": "basic",
					"basic": [
						{
							"key": "password",
							"value": "test",
							"type": "string"
						},
						{
							"key": "username",
							"value": "test",
							"type": "string"
						}
					]
				},
				"method": "POST",
				"header": [
					{
						"key": "x-test-header",
						"value": "{{x-test-header}}",
						"type": "text"
					},
					{
						"key": "x-json-test-header",
						"value": "{{x-json-test-header}}",
						"type": "text"
					},
					{
						"key": "x-string-header",
						"value": "{{x-string-header}}",
						"type": "text"
					},
					{
						"key": "Content-Type",
						"value": "application/json",
						"type": "text"
					},
					{
						"key": "Accept-Charset",
						"value": "UTF-8",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\r\n    \"someField\": \"SomeValue\"\r\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1",
					"protocol": "https",
					"host": [
						"run",
						"mocky",
						"io"
					],
					"path": [
						"v3",
						"64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
					]
				}
			},
			"response": [
				{
					"name": "POST",
					"originalRequest": {
						"method": "POST",
						"header": [
							{
								"key": "x-test-header",
								"value": "1245678",
								"type": "text"
							},
							{
								"key": "x-json-test-header",
								"value": "{\"a\":\"b\"}",
								"type": "text"
							},
							{
								"key": "x-string-header",
								"value": "asdsadasd",
								"type": "text"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"someField\": \"SomeValue\"\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1",
							"protocol": "https",
							"host": [
								"run",
								"mocky",
								"io"
							],
							"path": [
								"v3",
								"64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
							]
						}
					},
					"status": "OK",
					"code": 200,
					"_postman_previewlanguage": "json",
					"header": [
						{
							"key": "x-some-header",
							"value": "1234"
						},
						{
							"key": "Content-Type",
							"value": "application/json; charset=UTF-8"
						},
						{
							"key": "Date",
							"value": "Sat, 20 Feb 2021 14:53:15 GMT"
						},
						{
							"key": "Content-Length",
							"value": "27"
						},
						{
							"key": "Sozu-Id",
							"value": "9429821c-bc5a-4a36-b87e-da74fc2b086c"
						}
					],
					"cookie": [],
					"body": "{\n    \"someField\": \"SomeValue\"\n}"
				}
			]
		},
		{
			"name": "PUT",
			"request": {
				"auth": {
					"type": "basic",
					"basic": [
						{
							"key": "password",
							"value": "test",
							"type": "string"
						},
						{
							"key": "username",
							"value": "test",
							"type": "string"
						}
					]
				},
				"method": "PUT",
				"header": [
					{
						"key": "x-test-header",
						"value": "{{x-test-header}}",
						"type": "text"
					},
					{
						"key": "x-json-test-header",
						"value": "{{x-json-test-header}}",
						"type": "text"
					},
					{
						"key": "x-string-header",
						"value": "{{x-string-header}}",
						"type": "text"
					},
					{
						"key": "Content-Type",
						"value": "application/json",
						"type": "text"
					},
					{
						"key": "Accept-Charset",
						"value": "UTF-8",
						"type": "text"
					}
				],
				"body": {
					"mode": "raw",
					"raw": "{\r\n    \"someField\": \"SomeValue\"\r\n}",
					"options": {
						"raw": {
							"language": "json"
						}
					}
				},
				"url": {
					"raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1",
					"protocol": "https",
					"host": [
						"run",
						"mocky",
						"io"
					],
					"path": [
						"v3",
						"64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
					]
				}
			},
			"response": [
				{
					"name": "PUT",
					"originalRequest": {
						"method": "PUT",
						"header": [
							{
								"key": "x-test-header",
								"value": "1245678",
								"type": "text"
							},
							{
								"key": "x-json-test-header",
								"value": "{\"a\":\"b\"}",
								"type": "text"
							},
							{
								"key": "x-string-header",
								"value": "asdsadasd",
								"type": "text"
							}
						],
						"body": {
							"mode": "raw",
							"raw": "{\r\n    \"someField\": \"SomeValue\"\r\n}",
							"options": {
								"raw": {
									"language": "json"
								}
							}
						},
						"url": {
							"raw": "https://run.mocky.io/v3/64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1",
							"protocol": "https",
							"host": [
								"run",
								"mocky",
								"io"
							],
							"path": [
								"v3",
								"64724bb0-2dfb-4455-a6b8-8b78c5a6eaa1"
							]
						}
					},
					"status": "OK",
					"code": 200,
					"_postman_previewlanguage": "json",
					"header": [
						{
							"key": "x-some-header",
							"value": "1234"
						},
						{
							"key": "Content-Type",
							"value": "application/json; charset=UTF-8"
						},
						{
							"key": "Date",
							"value": "Sat, 20 Feb 2021 14:52:51 GMT"
						},
						{
							"key": "Content-Length",
							"value": "27"
						},
						{
							"key": "Sozu-Id",
							"value": "058e069d-06b7-4b0c-9f8f-6aad44bece5f"
						}
					],
					"cookie": [],
					"body": "{\n    \"someField\": \"SomeValue\"\n}"
				}
			]
		}
	],
	"auth": {
		"type": "basic",
		"basic": [
			{
				"key": "password",
				"value": "wisdominmyheart7322",
				"type": "string"
			},
			{
				"key": "username",
				"value": "rest",
				"type": "string"
			}
		]
	},
	"event": [
		{
			"listen": "prerequest",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		},
		{
			"listen": "test",
			"script": {
				"type": "text/javascript",
				"exec": [
					""
				]
			}
		}
	],
	"variable": [
		{
			"key": "x-test-header",
			"value": "1245678"
		},
		{
			"key": "x-json-test-header",
			"value": "{\"a\":\"b\"}"
		},
		{
			"key": "x-string-header",
			"value": "asdsadasd"
		},
		{
			"key": "Content-Type",
			"value": "application/json"
		},
		{
			"key": "Accept-Charset",
			"value": "UTF-8"
		}
	]
}

=== esgaltur/soapui2postman/TestProject-soapui-project.xml_processed.json
{"info":{"name":"https://run.mocky.io","_postman_id":"97c7d9d6-6c1c-4f74-857d-8abf5949f2f0","schema":"https://schema.getpostman.com/json/collection/v2.1.0/collection.json"},"item":[{"name":"GET","variable":[],"event":[],"request":{"url":{"query":[{"key":"a","value":"1","disabled":false}],"variable":[]},"auth":{"type":"basic","apikey":[],"awsv4":[],"basic":[{"key":"username","value":"test","type":"string"},{"key":"password","value":"test","type":"string"}],"bearer":[],"digest":[],"edgegrid":[],"hawk":[],"ntlm":[],"oauth1":[],"oauth2":[]},"method":"GET","header":[{"key":"x-str-test-header","value":"sdafghjhk","disabled":false,"description":""},{"key":"x-some-test-header","value":"123456","disabled":false,"description":""},{"key":"x-json-test-header","value":"{\"a\":\"b\"}","disabled":false,"description":""}],"body":{"mode":"raw","raw":"","urlencoded":[],"formdata":[],"options":{"raw":{"language":"json"}},"disabled":false}},"response":[]},{"name":"POST","variable":[],"event":[],"request":{"url":{"query":[{"key":"x-test-json-header","value":"{\"a\":\"b\"}","disabled":false},{"key":"a","value":"","disabled":false}],"variable":[]},"auth":{"type":"basic","apikey":[],"awsv4":[],"basic":[{"key":"username","value":"test","type":"string"},{"key":"password","value":"test","type":"string"}],"bearer":[],"digest":[],"edgegrid":[],"hawk":[],"ntlm":[],"oauth1":[],"oauth2":[]},"method":"POST","header":[{"key":"x-test-header","value":"123456","disabled":false,"description":""},{"key":"x-test-json-header","value":"{\"a\":\"b\"}","disabled":false,"description":""},{"key":"x-str-header","value":"asdfg","disabled":false,"description":""}],"body":{"mode":"raw","raw":"{\"someField\": \"SomeValue\"}","urlencoded":[],"formdata":[],"options":{"raw":{"language":"json"}},"disabled":false}},"response":[]},{"name":"PUT","variable":[],"event":[],"request":{"url":{"query":[{"key":"x-test-json-header","value":"{\"a\":\"b\"}","disabled":false},{"key":"a","value":"","disabled":false}],"variable":[]},"auth":{"type":"basic","apikey":[],"awsv4":[],"basic":[{"key":"username","value":"test","type":"string"},{"key":"password","value":"test","type":"string"}],"bearer":[],"digest":[],"edgegrid":[],"hawk":[],"ntlm":[],"oauth1":[],"oauth2":[]},"method":"PUT","header":[{"key":"x-test-header","value":"123456789","disabled":false,"description":""},{"key":"x-test-json-header","value":"{\"a\":\"b\"}","disabled":false,"description":""},{"key":"x-str-header","value":"asdfghj","disabled":false,"description":""}],"body":{"mode":"raw","raw":"{\"someField\": \"SomeValue\"}","urlencoded":[],"formdata":[],"options":{"raw":{"language":"json"}},"disabled":false}},"response":[]}],"event":[],"variable":[]}
